<a href="https://colab.research.google.com/github/tanusattri/Python-Code-Practice-/blob/main/Python_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(6+4*10)
print((6+4)*10)

46
100


In [ ]:
a= 15/2.0
print(type(a))

<class 'float'>


In [ ]:
a= eval(input("Enter first no:"))
b= eval(input("Enter second no:"))
print(a+b)

Enter first no:25
Enter second no:41
66


In [ ]:
d= 450
s= eval(input("Enter the speed:"))
t= d/s
print(t)

Enter the speed:60
7.5


In [ ]:
t= 5
p= eval(input("Enter the principal:"))
r= eval(input("Enter the rate:"))
si= (p*r*t)/100
amount= p+si
print(si)
print(amount)

Enter the principal:20000
Enter the rate:6.2
6200.0
26200.0


In [ ]:
print("Hello"+"Python")

HelloPython


In [ ]:
print('H' in 'Hello')

True


In [ ]:
def voidPrint():
  print("HELLO")
voidPrint()

HELLO


In [ ]:
year= eval(input("Enter the year"))
if((year%400==0) or (year%100!=0 and year%4==0)):
  print("Leap Year")
else:
  print("Not a Leap Year")

Enter the year2026
Not a Leap Year


In [ ]:
cels= eval(input("Enter the temperature in celsius:"))
far= (cels*9/5)+32
print(far)

Enter the temperature in celsius:36
96.8


In [ ]:
x,y= 20, 60
x,y = y, x+20
print(x,y)

60 40


In [ ]:
cost_price= eval(input("Enter the cost price:"))
profit= eval(input("Enter the profit:"))
selling_price= cost_price+profit
print(selling_price)

Enter the cost price:250
Enter the profit:50
300


In [ ]:
a= 20
b= 30
print((a+b)/2)

25.0


In [ ]:
ig= 100//32
print(ig)

3


In [ ]:
def calculate_area(base, height, type):
  if(type=='triangle'):
    area= (1/2)*base*height
    print(area)
  elif(type=='rectangle'):
    area= base*height
    print(area)
  else:
    print("Invalid type")
calculate_area(10,20,'triangle')
calculate_area(10,20, 'rectangle')

100.0
200


In [ ]:
radius= eval(input("Enter the radius:"))
area= 3.14*radius*radius
print(area)

Enter the radius:25
1962.5


In [ ]:
marks1= eval(input("Enter the marks of subject-1:"))
marks2= eval(input("Enter the marks of subject-2:"))
marks3= eval(input("Enter the marks of subject-3:"))
marks4= eval(input("Enter the marks of subject-4:"))
marks5= eval(input("Enter the marks of subject-5:"))
total= marks1+marks2+marks3+marks4+marks5
avg= (total)/5
print(total, avg)

Enter the marks of subject-1:25
Enter the marks of subject-2:55
Enter the marks of subject-3:85
Enter the marks of subject-4:78
Enter the marks of subject-5:6
249 49.8


In [ ]:
num= eval(input("Enter the number:"))
for i in range (1,6):
  print(num*i)

Enter the number:5
5
10
15
20
25


In [ ]:
name= input("Enter the name:")
cl= input("Enter the class:")
age= int(input("Enter the age:"))
print(name, cl, age)
print(name + "\n" + cl + "\n" + str(age))

Enter the name:xyz
Enter the class:12
Enter the age:15
xyz 12 15
xyz
12
15


In [ ]:
n1= int(input("Enter the first no:"))
n2= int(input("Enter the second no:"))
n3= int(input("Enter the third no:"))
sum1= n1+n2
sum2= n2+n3
n1= sum1
n2= sum2
print(n1, n2)

Enter the first no:2
Enter the second no:3
Enter the third no:4
5 7


In [ ]:
a,b,c= 10,10,10
print(a,b,c)
x= 20
x= x-5
y=x
print(y)

10 10 10
15


In [ ]:
age= int(input("Enter the age:"))
if (age>=18):
  print("Eligible")
else:
  print("Not Eligible")

Enter the age:20
Eligible


In [ ]:
num= int(input("Enter the number:"))
if(num%2==0):
  print("Even")
else:
  print("Not Even")

Enter the number:20
Even


In [ ]:
marks= int(input("Enter the marks:"))
if(marks>85):
  print("Grade A")
elif(marks>70 and marks<=85):
  print("Grade B")
elif(marks>60 and marks<=70):
  print("Grade C")
elif(marks>45 and marks<=60):
  print("Grade D")
else:
  print("Grade E")

Enter the marks:79
Grade B


In [ ]:
num= int(input("Enter the number:"))
if(num==0):
  print("Number is zero")
elif(num>0):
  print("Number is positive")
else:
  print("Number is negative")

Enter the number:5
Number is positive


In [ ]:
for letter in 'PYTHON':
  print(letter)

P
Y
T
H
O
N


In [ ]:
arr= [10,20, 30, 40, 50]
for n in arr:
  if n%2==0:
    print(n,'is a even number')

10 is a even number
20 is a even number
30 is a even number
40 is a even number
50 is a even number


In [ ]:
for i in range(1,11):
  print('3 X', i, '=', 3*i)

3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27
3 X 10 = 30


In [ ]:
num= int(input("Enter the number:"))
fact= 1
for i in range(num):
  fact= fact*(i+1)
print("Factorial is:", fact)

Enter the number:5
Factorial is: 120


In [ ]:
num= int(input("Enter the number:"))
i=0
while (i<=10):
  print(num,'X',i,'=', num*i)
  i=i+1

Enter the number:3
3 X 0 = 0
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27
3 X 10 = 30


In [ ]:
num1= int(input("Enter the first number:"))
num2= int(input("Enter the second number:"))
num3= int(input("Enter the third number:"))
if(num1>num2 and num1>num3):
  print("Largest number:", num1)
elif(num2>num1 and num2>num3):
  print("Largest number:", num2)
else:
  print("Largest number:", num3)

Enter the first number:10
Enter the second number:20
Enter the third number:30
Largest number: 30


In [ ]:
side1= int(input("Enter the first side:"))
side2= int(input("Enter the second side:"))
side3= int(input("Enter the third side:"))
if(side1+side2>side3 and side2+side3>side2 and side1+side3>side2):
  print("Triangle is valid")
else:
  print("Not valid")

Enter the first side:10
Enter the second side:0
Enter the third side:0
Not valid


In [ ]:
x=0
while (x<5):
  print(x)
  x= x+1

0
1
2
3
4


In [ ]:
ch= input("Enter the character:")
if(ch=='a' or ch=='A'):
  print("Vowel")
elif(ch=='e' or ch=='E'):
  print('Vowel')
elif(ch=='i' or ch=='I'):
  print('Vowel')
elif (ch=='o' or ch=='O'):
  print('Vowel')
elif( ch=='u' or ch=='U'):
  print('Vowel')
else:
  print("Consonant")

Enter the character:t
Consonant


In [ ]:
l1= list('computer')
print(l1)
l1[3]

['c', 'o', 'm', 'p', 'u', 't', 'e', 'r']


'p'

In [ ]:
l2= [10,2,4,5,6,20,40]
sum=0
for i in l2:
  sum= sum+i
print(sum)

87


In [ ]:
import numpy as np
data= np.random.randn(2,3)
print(data)

[[-0.16003883 -0.57761364 -0.7081127 ]
 [-0.58404845 -1.08931873 -0.13803489]]


In [ ]:
data= data*10
print(data)

[[ -1.60038832  -5.77613636  -7.08112698]
 [ -5.84048451 -10.8931873   -1.38034895]]


In [ ]:
data= data+data
print(data)

[[ -3.20077665 -11.55227273 -14.16225397]
 [-11.68096902 -21.7863746   -2.7606979 ]]


In [ ]:
data.shape
data.dtype
data.ndim

2

In [ ]:
data1= [10,20,0,30,40,50]
arr1= np.array(data1)
print(arr1)

[10 20  0 30 40 50]


In [ ]:
data2= [[0,1,2,3,4,5],[10,20,30,40,0,50]]
arr2= np.array(data2)
print(arr2)

[[ 0  1  2  3  4  5]
 [10 20 30 40  0 50]]


In [ ]:
data3= np.empty((2,3))
print(data3)

[[0.000000e+000 4.940656e-324 9.881313e-324]
 [4.940642e-318 4.940647e-318 4.940652e-318]]


In [ ]:
data4= np.zeros((2,3))
print(data4)
data4.dtype

[[0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [ ]:
data5= np.ones((2,3), dtype= int)
print(data5)

[[1 1 1]
 [1 1 1]]


In [ ]:
data6= np.arange(2,7)
print(data6)

[2 3 4 5 6]


In [ ]:
data7= np.full((2,3),8)
print(data7)

[[8 8 8]
 [8 8 8]]


In [ ]:
arr1= np.array([1,2,3], dtype= np.float64)
print(arr1)

[1. 2. 3.]


In [ ]:
arr= np.array([[1,2,3],[4,5,6]], dtype= np.float64)
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
arr_2= np.array([[1,2,3],[4,5,10]],dtype= np.float64)
arr_2>arr

array([[False, False, False],
       [False, False,  True]])

In [ ]:
arr2= arr**0.5
print(arr2)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [ ]:
arr= np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr_copy= arr[5:8].copy()
arr_copy[:]= 12
print(arr_copy)

[12 12 12]


In [ ]:
arr2d  = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2] #row extracts
arr2d[0][2]
arr2d[0,2]
arr2d[0]

array([1, 2, 3])

In [ ]:
arr_copy = arr2d[0].copy()
arr2d[0] = 42
arr2d

array([[42, 42, 42],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
arr2d[0]=arr_copy
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr= np.array([64,64,64,64,64,64,64,64,64,64])
print(arr)

[64 64 64 64 64 64 64 64 64 64]


In [ ]:
arr[1:6]

array([64, 64, 64, 64, 64])

In [ ]:
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr2d[1,:3]

array([4, 5, 6])

In [ ]:
arr2d[:3,2]

array([3, 6, 9])

In [ ]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names =='Bob'

array([ True, False, False,  True, False, False, False])

In [ ]:
names[names != 'Bob']

array(['Joe', 'Will', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [ ]:
data = np.random.randn(7,4)
data

array([[-0.70822387,  1.00610733, -1.34768399, -0.25741056],
       [ 0.25295194,  1.9281419 , -0.79798797,  1.40223691],
       [-0.4174855 , -0.75592604,  0.21941078,  0.75034758],
       [ 0.96143698, -0.89955397, -1.80664916, -0.33218162],
       [-1.95166446,  0.83605071,  0.61189292, -2.50032423],
       [-0.06701614, -0.36676646, -0.1511873 ,  0.11661031],
       [ 0.78516458, -0.34592527,  0.13527813,  0.87474718]])

In [ ]:
data[names=='Bob']

array([[-0.70822387,  1.00610733, -1.34768399, -0.25741056],
       [ 0.96143698, -0.89955397, -1.80664916, -0.33218162]])

In [ ]:
data[names == 'Bob', 2:]

array([[-1.34768399, -0.25741056],
       [-1.80664916, -0.33218162]])

In [ ]:
data[names == 'Bob', 3]

array([-0.25741056, -0.33218162])

In [ ]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [ ]:
data[~(names == 'Bob')]

array([[ 0.25295194,  1.9281419 , -0.79798797,  1.40223691],
       [-0.4174855 , -0.75592604,  0.21941078,  0.75034758],
       [-1.95166446,  0.83605071,  0.61189292, -2.50032423],
       [-0.06701614, -0.36676646, -0.1511873 ,  0.11661031],
       [ 0.78516458, -0.34592527,  0.13527813,  0.87474718]])

In [ ]:
arr = np.empty((8,4))

for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
arr[[4,3,0,2]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [2., 2., 2., 2.]])

In [ ]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [ ]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [ ]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [ ]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [ ]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
x = np.random.randn(8)
y = np.random.randn(8)
print (x)
print (y)

[-0.14294668  0.71781608  1.78025448  0.1913046  -0.35152504  0.9441935
  0.62870256 -0.47101452]
[ 0.26439117  0.38535301 -0.92861874 -1.61284149 -0.0085307   0.57405342
  0.6491732   0.41687041]


In [ ]:
np.maximum(x,y)

array([ 0.26439117,  0.71781608,  1.78025448,  0.1913046 , -0.0085307 ,
        0.9441935 ,  0.6491732 ,  0.41687041])

In [ ]:
remainder, whole_part = np.modf(arr)
print(remainder)
print(whole_part)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)
print(ys)

[[-5.   -5.   -5.   ... -5.   -5.   -5.  ]
 [-4.99 -4.99 -4.99 ... -4.99 -4.99 -4.99]
 [-4.98 -4.98 -4.98 ... -4.98 -4.98 -4.98]
 ...
 [ 4.97  4.97  4.97 ...  4.97  4.97  4.97]
 [ 4.98  4.98  4.98 ...  4.98  4.98  4.98]
 [ 4.99  4.99  4.99 ...  4.99  4.99  4.99]]


In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = [(x if c else y)
         for x, y, c in zip(xarr, yarr, cond)]
result

[np.float64(1.1),
 np.float64(2.2),
 np.float64(1.3),
 np.float64(1.4),
 np.float64(2.5)]

In [ ]:
arr = np.array([0,1,2,3,45,6,7])
arr.cumsum()

array([ 0,  1,  3,  6, 51, 57, 64])

In [ ]:
values = np.array([6,0,0,2,3,5,6])
np.in1d(values, [2,3,6])

/tmp/ipython-input-2804279729.py:2: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(values, [2,3,6])


array([ True, False, False,  True,  True, False,  True])

In [ ]:
import pandas as pd
obj= pd.Series([1,2,3,4,5])
print(obj)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])
obj2

,0
d,4
b,7
a,-5
c,3


In [ ]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [ ]:
obj2.values

array([ 4,  7, -5,  3])

In [ ]:
obj2['a']

np.int64(-5)

In [ ]:
obj2['d'] = 6
obj2[['c','a','d']]

,0
c,3
a,-5
d,6


In [ ]:
obj2[obj2 > 0]

,0
d,6
b,7
c,3


In [ ]:
obj2 * 2

,0
d,12
b,14
a,-10
c,6


In [ ]:
import numpy as np
np.exp(obj2)

,0
d,403.428793
b,1096.633158
a,0.006738
c,20.085537


In [ ]:
sdata = {'Ohio': 3500, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
obj3 = pd.Series(sdata)
obj3

,0
Ohio,3500
Texas,71000
Oregon,16000
Utah,5000


In [ ]:
states = ['California','Ohio','Oregon','Texas']
obj4 = pd.Series(sdata, index=states)
obj4

,0
California,NaN
Ohio,3500.0
Oregon,16000.0
Texas,71000.0


In [ ]:
pd.isnull(obj4)

,0
California,True
Ohio,False
Oregon,False
Texas,False


In [ ]:
pd.notnull(obj4)

,0
California,False
Ohio,True
Oregon,True
Texas,True


In [ ]:
obj3 + obj4

,0
California,NaN
Ohio,7000.0
Oregon,32000.0
Texas,142000.0
Utah,NaN


In [ ]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

,population
state,
California,NaN
Ohio,3500.0
Oregon,16000.0
Texas,71000.0


In [ ]:
import pandas as pd
f= {'name':['x','y','z'],'age':[12,14,16]}
df= pd.DataFrame(f)
print(df)

  name  age
0    x   12
1    y   14
2    z   16


In [ ]:
df.head()

,name,age
0,x,12
1,y,14
2,z,16


In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year' : [2000, 2001, 2002, 2001, 2002, 2003],
       'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
print(frame)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2


In [ ]:
frame.head()

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9


In [ ]:
pd.DataFrame(data, columns=['year', 'state','pop'])

,year,state,pop
0,2000,Ohio,1.5
1,2001,Ohio,1.7
2,2002,Ohio,3.6
3,2001,Nevada,2.4
4,2002,Nevada,2.9
5,2003,Nevada,3.2


In [ ]:
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'],
                     index = ['one', 'two', 'three', 'four', 'five', 'six'])
print(frame2)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN


In [ ]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
frame2.loc['three']

,three
year,2002
state,Ohio
pop,3.6
debt,NaN


In [ ]:
frame2['debt'] = 16.5
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,16.5
two,2001,Ohio,1.7,16.5
three,2002,Ohio,3.6,16.5
four,2001,Nevada,2.4,16.5
five,2002,Nevada,2.9,16.5
six,2003,Nevada,3.2,16.5


In [ ]:
import numpy as np
frame2['debt'] = np.arange(6.0)
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,0.0
two,2001,Ohio,1.7,1.0
three,2002,Ohio,3.6,2.0
four,2001,Nevada,2.4,3.0
five,2002,Nevada,2.9,4.0
six,2003,Nevada,3.2,5.0


In [ ]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two','four','five'])
frame2['debt'] = val
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,NaN
two,2001,Ohio,1.7,-1.2
three,2002,Ohio,3.6,NaN
four,2001,Nevada,2.4,-1.5
five,2002,Nevada,2.9,-1.7
six,2003,Nevada,3.2,NaN


In [ ]:
frame2['eastern'] = frame2.state == 'Ohio' #create a new column with name 'eastern' and contains True and False value of 'Ohio' data present or not
frame2

,year,state,pop,debt,eastern
one,2000,Ohio,1.5,NaN,True
two,2001,Ohio,1.7,-1.2,True
three,2002,Ohio,3.6,NaN,True
four,2001,Nevada,2.4,-1.5,False
five,2002,Nevada,2.9,-1.7,False
six,2003,Nevada,3.2,NaN,False


In [ ]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

,Nevada,Ohio
2001,2.4,1.7
2002,2.9,3.6
2000,NaN,1.5


In [ ]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

,Ohio,Nevada
2001,1.7,2.4
2002,3.6,2.9


In [ ]:
frame3.T

,2001,2002,2000
Nevada,2.4,2.9,NaN
Ohio,1.7,3.6,1.5


In [ ]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [ ]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [ ]:
obj = pd.Series(range(3), index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [ ]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [ ]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)
obj2

,0
0,1.5
1,-2.5
2,0.0


In [ ]:
obj2.index is labels

True

In [ ]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [ ]:
'Ohio' in frame3.columns

True

In [ ]:
2003 in frame3.columns

False

In [ ]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [ ]:
obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])
obj

,0
a,0.0
b,1.0
c,2.0
d,3.0
e,4.0


In [ ]:
new_obj = obj.drop('c')
new_obj

,0
a,0.0
b,1.0
d,3.0
e,4.0


In [ ]:
obj.drop(['d','c'])

,0
a,0.0
b,1.0
e,4.0


In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio','Colorado','Utah','New York'],
                   columns = ['one','two','three','four'])
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [ ]:
data.drop(['Colorado', 'Ohio'])

,one,two,three,four
Utah,8,9,10,11
New York,12,13,14,15


In [ ]:
data.drop('two', axis=1)

,one,three,four
Ohio,0,2,3
Colorado,4,6,7
Utah,8,10,11
New York,12,14,15


In [ ]:
data.drop(['two','four'], axis='columns')

,one,three
Ohio,0,2
Colorado,4,6
Utah,8,10
New York,12,14


In [ ]:
obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])
obj.drop('c', inplace=True)
obj

,0
a,0.0
b,1.0
d,3.0
e,4.0


In [ ]:
obj = pd.Series(np.arange(4.), index = ['a','b','c','d'])
obj

,0
a,0.0
b,1.0
c,2.0
d,3.0


In [ ]:
obj['b']

np.float64(1.0)

In [ ]:
obj[1]

/tmp/ipython-input-2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


np.float64(1.0)

In [ ]:
obj[2:4]

,0
c,2.0
d,3.0


In [ ]:
obj[['b','a','d']]

,0
b,1.0
a,0.0
d,3.0


In [ ]:
obj[[1,3]]

/tmp/ipython-input-1781339481.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1,3]]


,0
b,1.0
d,3.0


In [ ]:
obj[obj < 2]

,0
a,0.0
b,1.0


In [ ]:
obj['b':'c']

,0
b,1.0
c,2.0


In [ ]:
obj['b':'c'] = 5
obj

,0
a,0.0
b,5.0
c,5.0
d,3.0


In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio','Colorado','Utah','New York'],
                   columns = ['one','two','three','four'])
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [ ]:
data['two']

,two
Ohio,1
Colorado,5
Utah,9
New York,13


In [ ]:
data[['three', 'one']]

,three,one
Ohio,2,0
Colorado,6,4
Utah,10,8
New York,14,12


In [ ]:
data[data['three'] > 5]

,one,two,three,four
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [ ]:
data < 5

,one,two,three,four
Ohio,True,True,True,True
Colorado,True,False,False,False
Utah,False,False,False,False
New York,False,False,False,False


In [ ]:
data[data < 5] = 0
data

,one,two,three,four
Ohio,0,0,0,0
Colorado,0,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [ ]:
import pandas as pd
import numpy as np

data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio','Colorado','Utah','New York'],
                   columns = ['one','two','three','four'])
data[data < 5] = 0
data.loc[:'Utah', 'two']

,two
Ohio,0
Colorado,5
Utah,9


In [ ]:
import pandas as pd
import numpy as np
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio','Colorado','Utah','New York'],
                   columns = ['one','two','three','four'])
data['two']

,two
Ohio,1
Colorado,5
Utah,9
New York,13


In [ ]:
data[['three', 'one']]

,three,one
Ohio,2,0
Colorado,6,4
Utah,10,8
New York,14,12


In [ ]:
data[data['three'] > 5]

,one,two,three,four
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [ ]:
data < 5

,one,two,three,four
Ohio,True,True,True,True
Colorado,True,False,False,False
Utah,False,False,False,False
New York,False,False,False,False


In [ ]:
data[data < 5] = 0
data

,one,two,three,four
Ohio,0,0,0,0
Colorado,0,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [ ]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a','c','d','e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a','c','e','f','g'])
print(s1)
print(s2)

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64


In [ ]:
s1 + s2

,0
a,5.2
c,1.1
d,NaN
e,0.0
f,NaN
g,NaN


In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(df1)
print(df2)

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0
          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0


In [ ]:
df1 + df2

,b,c,d,e
Colorado,NaN,NaN,NaN,NaN
Ohio,3.0,NaN,6.0,NaN
Oregon,NaN,NaN,NaN,NaN
Texas,9.0,NaN,12.0,NaN
Utah,NaN,NaN,NaN,NaN


In [ ]:
df1 = pd.DataFrame({'A': [1,2]})
df2 = pd.DataFrame({'B': [3,4]})
print(df1)
print(df2)

   A
0  1
1  2
   B
0  3
1  4


In [ ]:
df1 - df2

,A,B
0,NaN,NaN
1,NaN,NaN


In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))
print(df1)
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [ ]:
df1+df2

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,NaN
1,9.0,11.0,13.0,15.0,NaN
2,18.0,20.0,22.0,24.0,NaN
3,NaN,NaN,NaN,NaN,NaN


In [ ]:
df1.add(df2, fill_value=0)

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,4.0
1,9.0,11.0,13.0,15.0,9.0
2,18.0,20.0,22.0,24.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [ ]:
1/df1

,a,b,c,d
0,inf,1.000000,0.500000,0.333333
1,0.250,0.200000,0.166667,0.142857
2,0.125,0.111111,0.100000,0.090909


In [ ]:
df1.rdiv(1)

,a,b,c,d
0,inf,1.000000,0.500000,0.333333
1,0.250,0.200000,0.166667,0.142857
2,0.125,0.111111,0.100000,0.090909


In [ ]:
df1.reindex(columns = df2.columns, fill_value=0)

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,0
1,4.0,5.0,6.0,7.0,0
2,8.0,9.0,10.0,11.0,0


In [ ]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [ ]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    columns=list('bde'),
                    index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
print(frame)
print(series)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64


In [ ]:
frame - series

,b,d,e
Utah,0.0,0.0,0.0
Ohio,3.0,3.0,3.0
Texas,6.0,6.0,6.0
Oregon,9.0,9.0,9.0


In [ ]:
series2 = pd.Series(range(3), index=['b','e','f'])
frame + series2

,b,d,e,f
Utah,0.0,NaN,3.0,NaN
Ohio,3.0,NaN,6.0,NaN
Texas,6.0,NaN,9.0,NaN
Oregon,9.0,NaN,12.0,NaN


In [ ]:
series3 = frame['d']
series3

,d
Utah,1.0
Ohio,4.0
Texas,7.0
Oregon,10.0


In [ ]:
frame

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [ ]:
frame.sub(series3, axis='index')

,b,d,e
Utah,-1.0,0.0,1.0
Ohio,-1.0,0.0,1.0
Texas,-1.0,0.0,1.0
Oregon,-1.0,0.0,1.0


In [ ]:
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

,b,d,e
Utah,-2.002896,-1.984480,-0.153984
Ohio,-0.266134,0.438862,-0.236348
Texas,-1.258901,0.559928,-0.854908
Oregon,-1.615284,0.852958,1.700622


In [ ]:
import numpy as np
np.abs(frame)

,b,d,e
Utah,2.002896,1.984480,0.153984
Ohio,0.266134,0.438862,0.236348
Texas,1.258901,0.559928,0.854908
Oregon,1.615284,0.852958,1.700622


In [ ]:
f = lambda x: x.max() - x.min()
frame.apply(f)

,0
b,1.736763
d,2.837437
e,2.555530


In [ ]:
frame.apply(f, axis='columns')

,0
Utah,1.848912
Ohio,0.704996
Texas,1.818829
Oregon,3.315905


In [ ]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min','max'])
frame.apply(f)

,b,d,e
min,-2.002896,-1.984480,-0.854908
max,-0.266134,0.852958,1.700622


In [ ]:
format = lambda x: '%.2f' % x
frame.applymap(format)

/tmp/ipython-input-1073433956.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(format)


,b,d,e
Utah,-2.00,-1.98,-0.15
Ohio,-0.27,0.44,-0.24
Texas,-1.26,0.56,-0.85
Oregon,-1.62,0.85,1.70


In [ ]:
frame['e'].map(format)

,e
Utah,-0.15
Ohio,-0.24
Texas,-0.85
Oregon,1.70


In [ ]:
obj = pd.Series(range(4), index=['d','a','b','c'])
obj.sort_index()

,0
a,1
b,2
c,3
d,0


In [ ]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index=['three','one'],
                    columns = ['d','a','b','c'])
frame.sort_index()

,d,a,b,c
one,4,5,6,7
three,0,1,2,3


In [ ]:
frame.sort_index(axis=1)

,a,b,c,d
three,1,2,3,0
one,5,6,7,4


In [ ]:
frame.sort_index(axis=1, ascending=False)

,d,c,b,a
three,0,3,2,1
one,4,7,6,5


In [ ]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

,0
4,-3.0
5,2.0
0,4.0
2,7.0
1,NaN
3,NaN


In [ ]:
frame = pd.DataFrame({'b': [4,7,-3,2], 'a':[0,1,0,1]})
frame

,b,a
0,4,0
1,7,1
2,-3,0
3,2,1


In [ ]:
frame.sort_values(by='b')

,b,a
2,-3,0
3,2,1
0,4,0
1,7,1


In [ ]:
frame.sort_values(by=['a','b'])

,b,a
2,-3,0
0,4,0
3,2,1
1,7,1


In [ ]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj.rank()

,0
0,6.5
1,1.0
2,6.5
3,4.5
4,3.0
5,2.0
6,4.5


In [ ]:
obj.rank(method='first')

,0
0,6.0
1,1.0
2,7.0
3,4.0
4,3.0
5,2.0
6,5.0


In [ ]:
obj.rank(ascending=False, method='max')

,0
0,2.0
1,7.0
2,2.0
3,4.0
4,5.0
5,6.0
6,4.0


In [ ]:
frame = pd.DataFrame({'b': [4.3,7,-3,2], 'a':[0,1,0,1],
                     'c': [-2,5,8,-2.5]})
frame

,b,a,c
0,4.3,0,-2.0
1,7.0,1,5.0
2,-3.0,0,8.0
3,2.0,1,-2.5


In [ ]:
frame.rank(axis='columns')

,b,a,c
0,3.0,2.0,1.0
1,3.0,1.0,2.0
2,1.0,2.0,3.0
3,3.0,2.0,1.0


In [ ]:
obj = pd.Series(range(5), index=['a','a','b','b','c'])
obj

,0
a,0
a,1
b,2
b,3
c,4


In [ ]:
import pandas as pd
import numpy as np
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

,b,d,e
Utah,1.358472,0.394306,0.541441
Ohio,-0.902651,0.871544,0.075267
Texas,-0.001950,-0.179669,0.250694
Oregon,-0.384277,1.510089,-0.827730


In [ ]:
obj = pd.Series(range(5), index=['a','a','b','b','c'])
obj

,0
a,0
a,1
b,2
b,3
c,4


In [ ]:
obj.index.is_unique

False

In [ ]:
obj['a']

,0
a,0
a,1


In [ ]:
obj['c']

np.int64(4)

In [ ]:
df = pd.DataFrame(np.random.randn(4,3), index=['a','a','b','b'])
df

,0,1,2
a,0.087165,1.058974,0.025305
a,0.314070,-1.351315,-0.093288
b,-2.756589,1.369916,-1.793302
b,0.766671,0.814085,0.759914


In [ ]:
df.loc['b']

,0,1,2
b,-2.756589,1.369916,-1.793302
b,0.766671,0.814085,0.759914


In [ ]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75,-1.3]],
                 index=['a','b','c','d'],
                 columns=['one','two'])
df

,one,two
a,1.40,NaN
b,7.10,-4.5
c,NaN,NaN
d,0.75,-1.3


In [ ]:
df.sum()

,0
one,9.25
two,-5.80


In [ ]:
df.sum(axis='columns')

,0
a,1.40
b,2.60
c,0.00
d,-0.55


In [ ]:
df.mean(axis='columns', skipna=False)

,0
a,NaN
b,1.300
c,NaN
d,-0.275


In [ ]:
df.idxmax()

,0
one,b
two,d


In [ ]:
df.cumsum() #cumulative-sum

,one,two
a,1.40,NaN
b,8.50,-4.5
c,NaN,NaN
d,9.25,-5.8


In [ ]:
df.describe()

,one,two
count,3.000000,2.000000
mean,3.083333,-2.900000
std,3.493685,2.262742
min,0.750000,-4.500000
25%,1.075000,-3.700000
50%,1.400000,-2.900000
75%,4.250000,-2.100000
max,7.100000,-1.300000


In [ ]:
obj = pd.Series(['a','a','b','c'] * 4)
print(obj)

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object


In [ ]:
obj.describe()